- name: Update all packages  
  hosts: all
  become: true
  tasks:
  - name: updating packages
    command: sudo apt-get update -y

- hosts: jenkins
  become: true
  roles: 
#    - ansible     
    - angular-node-npm     
#    - git
#    - docker
#    - terraform
    - jenkins  
  tasks:
  - name: configuring user access
    command: sudo usermod -aG sudo mizan
